In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import math 
import seaborn as sns 

df=pd.read_csv('Social_Network_Ads.csv')
df 

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [2]:
df=df.iloc[:,2:]
df 

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop('Purchased', axis=1),df['Purchased'],test_size=0.9)

x_train.shape


(40, 2)

In [4]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()



scaler.fit(x_train)


StandardScaler()

In [5]:
from sklearn.preprocessing import StandardScaler 


scaler=StandardScaler()



df_scaled=scaler.fit_transform(df)
df_scaled

array([[-1.78179743, -1.49004624, -0.74593581],
       [-0.25358736, -1.46068138, -0.74593581],
       [-1.11320552, -0.78528968, -0.74593581],
       ...,
       [ 1.17910958, -1.46068138,  1.34059793],
       [-0.15807423, -1.07893824, -0.74593581],
       [ 1.08359645, -0.99084367,  1.34059793]])

In [11]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop('Purchased', axis=1),df['Purchased'],test_size=0.9)


scaler=StandardScaler()



x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

print("Mean and std of train set:", scaler.mean_, scaler.scale_)
print("Standardized training set:\n", x_train_scaled)
print("Standardized test set:\n", x_test_scaled)


Mean and std of train set: [3.8075e+01 6.1525e+04] [9.99846863e+00 3.01670246e+04]
Standardized training set:
 [[-0.3075471  -0.21629578]
 [-0.20753178 -0.05055189]
 [ 1.89278986 -1.17761034]
 [ 2.1928358   0.71187001]
 [-1.10766962 -1.47594934]
 [-1.10766962  0.91076267]
 [-1.30770026 -1.31020545]
 [-1.80777684 -0.84612256]
 [-1.20768494 -0.61408111]
 [-0.90763899 -1.11131278]
 [ 0.2925448  -0.34889089]
 [ 0.2925448   0.34723345]
 [ 0.69260606 -0.54778356]
 [-0.60759304 -1.44280056]
 [-0.90763899  0.71187001]
 [ 1.09266733 -1.11131278]
 [-0.70760836 -0.11684944]
 [ 1.39271328  0.94391145]
 [ 0.69260606 -0.97871767]
 [-0.10751646  0.57927489]
 [ 1.39271328  2.53505279]
 [-0.3075471   1.1759529 ]
 [ 0.39256012  0.94391145]
 [ 0.69260606 -1.31020545]
 [-0.10751646 -0.28259333]
 [ 1.99280517  1.10965534]
 [ 0.39256012  0.61242367]
 [-0.40756241 -0.61408111]
 [-1.30770026  0.94391145]
 [-0.70760836 -1.44280056]
 [-0.3075471   0.44667978]
 [ 1.59274391  0.28093589]
 [ 0.19252948  1.50744068

In [6]:
#Practice 

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np

# Sample dataset
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6]])
y = np.array([0, 1, 0, 1, 0])

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# StandardScaler
scaler = StandardScaler()

# Fit and transform on training set
X_train_scaled = scaler.fit_transform(X_train)

# Only transform on test set
X_test_scaled = scaler.transform(X_test)

print("Mean and std of train set:", scaler.mean_, scaler.scale_)
print("Standardized training set:\n", X_train_scaled)
print("Standardized test set:\n", X_test_scaled)


Mean and std of train set: [3.25 4.25] [1.47901995 1.47901995]
Standardized training set:
 [[ 1.18321596  1.18321596]
 [-0.16903085 -0.16903085]
 [-1.52127766 -1.52127766]
 [ 0.50709255  0.50709255]]
Standardized test set:
 [[-0.84515425 -0.84515425]]


In [13]:

# Sample dataset
data = np.array([[1.0, 2.0], [2.0, 4.0], [3.0, 6.0], [4.0, 8.0]])
labels = np.array([0, 1, 0, 1])

# Split the dataset
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.5, random_state=42)

# Initialize the scaler
scaler = StandardScaler()

# Fit the scaler on the training data
scaler.fit(x_train)

# Transform both training and test data
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

print("Training set scaled:\n", x_train_scaled)
print("Test set scaled:\n", x_test_scaled)


Training set scaled:
 [[-1. -1.]
 [ 1.  1.]]
Test set scaled:
 [[0. 0.]
 [2. 2.]]


In [16]:
#applying standardization in insurance dataset 


df=pd.read_csv('insurance2.csv')
#Preprocessing data 


df=df.iloc[:,[0,2,-2,-1]]
df 



age     bmi      charges  insuranceclaim
0      19  27.900  16884.92400               1
1      18  33.770   1725.55230               1
2      28  33.000   4449.46200               0
3      33  22.705  21984.47061               0
4      32  28.880   3866.85520               1
...   ...     ...          ...             ...
1333   50  30.970  10600.54830               0
1334   18  31.920   2205.98080               1
1335   18  36.850   1629.83350               1
1336   21  25.800   2007.94500               0
1337   61  29.070  29141.36030               1

[1338 rows x 4 columns]

In [17]:
#Features 
df.iloc[:,:3]

age     bmi      charges
0      19  27.900  16884.92400
1      18  33.770   1725.55230
2      28  33.000   4449.46200
3      33  22.705  21984.47061
4      32  28.880   3866.85520
...   ...     ...          ...
1333   50  30.970  10600.54830
1334   18  31.920   2205.98080
1335   18  36.850   1629.83350
1336   21  25.800   2007.94500
1337   61  29.070  29141.36030

[1338 rows x 3 columns]

In [19]:
# Labels 
df.iloc[:,-1]

0       1
1       1
2       0
3       0
4       1
       ..
1333    0
1334    1
1335    1
1336    0
1337    1
Name: insuranceclaim, Length: 1338, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:3],df.iloc[:,-1],train_size=0.9)


In [21]:
x_train

age     bmi      charges
16     52  30.780  10797.33620
853    53  23.750  11729.67950
713    20  40.470   1984.45330
303    28  33.000   4349.46200
598    43  32.600   7441.50100
...   ...     ...          ...
119    37  23.370   6686.43130
118    49  27.170   8601.32930
1328   23  24.225  22395.74424
1214   27  31.255   3956.07145
890    64  26.885  29330.98315

[1204 rows x 3 columns]

In [22]:
x_test

age     bmi      charges
1065   42  25.300   7045.49900
748    47  36.000   8556.90700
687    40  41.690   5438.74910
177    54  29.200  10436.09600
749    28  30.875   3062.50825
...   ...     ...          ...
678    56  36.100  12363.54700
207    35  27.740  20984.09360
855    20  29.600   1875.34400
1168   32  35.200   4670.64000
498    44  23.980   8211.10020

[134 rows x 3 columns]

In [23]:
y_train

16      1
853     0
713     1
303     0
598     0
       ..
119     0
118     1
1328    0
1214    1
890     1
Name: insuranceclaim, Length: 1204, dtype: int64

In [24]:
y_test

1065    0
748     1
687     1
177     0
749     1
       ..
678     0
207     0
855     1
1168    0
498     0
Name: insuranceclaim, Length: 134, dtype: int64

In [26]:
#Performing Standardization  

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

print("Mean and std of train set:", scaler.mean_, scaler.scale_)
print("Standardized training set:\n", x_train_scaled)
print("Standardized test set:\n", x_test_scaled)

Mean and std of train set: [   39.31893688    30.75494186 13393.14653703] [1.41125497e+01 6.04618193e+00 1.21538487e+04]
Standardized training set:
 [[ 0.89856641  0.00414446 -0.21357929]
 [ 0.96942533 -1.15857279 -0.13686751]
 [-1.36891896  1.60680877 -0.93868975]
 ...
 [-1.1563422  -1.08001081  0.74071991]
 [-0.87290653  0.08270643 -0.77646804]
 [ 1.74887342 -0.64006375  1.31134071]]
Standardized test set:
 [[ 0.18997723 -0.90221266 -0.52227469]
 [ 0.54427182  0.86749923 -0.39791836]
 [ 0.0482594   1.808589   -0.6544756 ]
 [ 1.04028424 -0.25717748 -0.24330158]
 [-0.80204762  0.01985685 -0.84998905]
 [ 0.33169507  0.26215853 -0.47387672]
 [-0.37689411 -1.94419255 -0.54633793]
 [ 0.54427182  2.77283389 -0.43683502]
 [-1.43977788  0.1926932   1.67495464]
 [-1.08548329 -1.17428518 -0.90836889]
 [-0.51861195 -0.48293979 -0.73546611]
 [-0.09345844  0.66902686 -0.56127098]
 [-0.30603519 -0.451515    0.56292524]
 [-0.44775303  0.45401514  1.94886624]
 [ 0.18997723 -0.73433812 -0.53088012]
 [